# Generated by Django 3.2.12 on 2023-10-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_sale_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_number',
            field=models.IntegerField(unique=True),
        ),
    ]
