# Generated by Django 3.2.12 on 2023-09-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
