# Generated by Django 3.2.12 on 2023-10-05 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_entry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='entry_date',
        ),
        migrations.AddField(
            model_name='inventory',
            name='notes',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, default='2023-10-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='transaction_type',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], default='2023-10-05', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
