# Generated by Django 3.2.12 on 2023-10-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20231005_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
    ]
