# Generated by Django 3.2.12 on 2023-10-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20231005_1500'),
        ('sales', '0002_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_detail_set', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='unit_price',
            field=models.FloatField(),
        ),
    ]
