# Generated by Django 3.2.12 on 2023-10-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_sale_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
